# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: microservices-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# MongoDB Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: microservices-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# MongoDB Config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config-pvc
  namespace: microservices-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

## persistent version, data will be persisted in target path even when pvc is deleted
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: postgres-pv
#spec:
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: postgres-storage
#  hostPath:
#    path: /data/postgres-inventory/db
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-pvc
#  namespace: microservices-lab
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
#  storageClassName: postgres-storage
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-data-pv
#spec:
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: mongodb-data-storage
#  hostPath:
#    path: /data/mongodb-order/db
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongodb-data-pvc
#  namespace: microservices-lab
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
#  storageClassName: mongodb-data-storage
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-config-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: mongodb-configdb-storage
#  hostPath:
#    path: /data/mongodb-order/configdb
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongodb-config-pvc
#  namespace: microservices-lab
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: mongodb-configdb-storage