apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: microservices-lab
type: Opaque
data:
  # echo -n "password" | base64
  postgres-password: cGFzc3dvcmQ=  # password
  postgres-user: cG9zdGdyZXM=     # postgres
  mongodb-username: cm9vdA==       # root
  mongodb-password: cGFzc3dvcmQ=   # password
---
apiVersion: v1
kind: Secret
metadata:
  name: mailtrap-secrets
  namespace: microservices-lab
type: Opaque
data:
  mailtrap-username: MzIwNTA3MjE1ZmQxYWY=  # 320507215fd1af
  mailtrap-password: ZmUwZjVjZTQ2MWY4YjA=  # fe0f5ce461f8b0